[tool.poetry]
name = "day1"
version = "0.1.0"
description = ""
authors = ["Koen Oosterwijk <koen.oosterwijk@demcon.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pandas = "^1.5.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
